kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: template-service-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard